export const topCollectionCards = [
	{
		id: 1,
		bgImage: '/static/assets/image/topCollection1.png',
		avatar: '/static/assets/image/avatar.png',
		verified: '/static/assets/image/google-verified.svg',
		boxImg1: '/static/assets/image/boxImg1.png',
		boxImg2: '/static/assets/image/boxImg2.png',
		boxImg3: '/static/assets/image/boxImg3.png',
	},
	{
		id: 2,
		bgImage: '/static/assets/image/topCollection1.png',
		avatar: '/static/assets/image/avatar.png',
		verified: '/static/assets/image/google-verified.svg',
		boxImg1: '/static/assets/image/boxImg1.png',
		boxImg2: '/static/assets/image/boxImg2.png',
		boxImg3: '/static/assets/image/boxImg3.png',
	},
	{
		id: 3,
		bgImage: '/static/assets/image/topCollection1.png',
		avatar: '/static/assets/image/avatar.png',
		verified: '/static/assets/image/google-verified.svg',
		boxImg1: '/static/assets/image/boxImg1.png',
		boxImg2: '/static/assets/image/boxImg2.png',
		boxImg3: '/static/assets/image/boxImg3.png',
	},
	{
		id: 4,
		bgImage: '/static/assets/image/topCollection1.png',
		avatar: '/static/assets/image/avatar.png',
		verified: '/static/assets/image/google-verified.svg',
		boxImg1: '/static/assets/image/boxImg1.png',
		boxImg2: '/static/assets/image/boxImg2.png',
		boxImg3: '/static/assets/image/boxImg3.png',
	},
]
